name: Run Docker Container

on: [push]

jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker image from GitHub Container Registry
        run: docker pull ghcr.io/xinruixie/ero_guro:philologic

      - name: Run Docker container
        run: docker run ghcr.io/xinruixie/ero_guro:philologic
